Repository CURIO-DEV/CURIO-FE, pull requests merged in 2025-04, with the labels that each got.

#5 [Feature/#3] 화면 레이아웃 구성
  public/file.svg
  public/globe.svg
  public/next.svg
  public/vercel.svg
  public/window.svg
  src/app/(route)/setting/page.tsx
  src/app/_components/.gitkeep
  src/app/_components/layout.tsx
  src/app/_components/sidebar.tsx
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/page.tsx
Labels: ✨ Feat, 💄 Style

#7 [Feature/#6] 로그인 전 사이드바 구현 및 공통 버튼 구현
  package.json
  pnpm-lock.yaml
  public/images/logo.png
  src/app/_components/button.tsx
  src/app/_components/layout.tsx
  src/app/_components/sidebar.tsx
  src/app/_constants/images.ts
  src/app/_types/.gitkeep
  src/app/_utils/.gitkeep
  src/app/_utils/cn.ts
  src/app/globals.css
Labels: 🌱 Add, ✨ Feat, 💄 Style

#9 [Feature/#8] 공통 모달 구현 및 메일 구독 신청 컴포넌트 구현
  next.config.ts
  package.json
  pnpm-lock.yaml
  public/assets/close.svg
  public/assets/index.ts
  public/assets/shortcut.svg
  src/app/_components/input.tsx
  src/app/_components/layout.tsx
  src/app/_components/modal.tsx
  src/app/_components/sidebar/index.tsx
  src/app/_components/sidebar/subscribe.tsx
  src/app/globals.css
  svgr.d.ts
  tsconfig.json
Labels: 🌱 Add, 🧹 Chore, ✨ Feat, 💄 Style

#10 [Feature/#4] 로그인 페이지 퍼블리싱
  src/app/(route)/login/page.tsx
  src/app/_components/layout.tsx
  src/app/globals.css
Labels: ✨ Feat, 💄 Style

#16 [Feature/#11] 헤더 구현 및 카테고리 컴포넌트 구현
  public/assets/edit.svg
  public/assets/search.svg
  src/app/(route)/home/_components/.gitkeep
  src/app/(route)/home/_components/banner.tsx
  src/app/(route)/home/_components/chip.tsx
  src/app/(route)/home/page.tsx
  src/app/_components/button.tsx
  src/app/_components/header.tsx
  src/app/_components/layout.tsx
  src/app/_constants/categories.ts
  src/app/page.tsx
Labels: 🌱 Add, ✨ Feat, 💄 Style

#18 [Hotfix/#17] 빌드 오류 해결
  next.config.ts
Labels: 🐛 Fix

#20 [Chore/#19] 자동 배포를 위한 GitHub Actions 설정 추가
  .github/workflows/deploy.yml
  build.sh
Labels: 🧹 Chore, 👷 CI

#13 [Feature/#12] 로그인 후 컴포넌트 구현
  public/assets/arrow-down.svg
  public/assets/arrow-up.svg
  public/assets/bookMark.svg
  public/assets/bookmark-g.svg
  public/assets/favorite-g.svg
  public/assets/favorite.svg
  public/assets/settings.svg
  public/images/logo-head.png
  public/images/newThums.png
  src/app/_components/sidebar/index.tsx
  src/app/_components/sidebar/profileCard.tsx
  src/app/_components/sidebar/trandRanking.tsx
  src/app/_components/sidebar/trandingNews.tsx
  src/app/_constants/images.ts
  src/app/_constants/routes.ts
  src/app/_mocks/dummyNews.ts
  src/app/_mocks/trends.ts
  tsconfig.json
Labels: 🌱 Add, ✨ Feat, 💄 Style

#22 [Bugfix/#21] 빌드 오류 해결
  build.sh
Labels: 🐛 Fix

#24 [Refactor/#23] 스타일 관련 리팩토링 및 홈 퍼블리싱
  .github/workflows/deploy.yml
  package.json
  pnpm-lock.yaml
  src/app/(route)/home/page.tsx
  src/app/(route)/login/page.tsx
  src/app/(route)/search/page.tsx
  src/app/_components/layout.tsx
  src/app/_components/sidebar/index.tsx
Labels: ♻️ Refactor, 💄 Style
