Repository CURIO-DEV/CURIO-FE, pull requests merged in 2025-05, with the labels that each got.

#28 [Bugfix/#27] svgr 오류 해결
  next.config.ts
  public/assets/arrowDown.svg
  public/assets/arrowUp.svg
  public/assets/bookmark-g.svg
  public/assets/favorite-g.svg
  public/assets/index.ts
  src/app/(route)/home/page.tsx
  src/app/_components/header.tsx
  src/app/_components/modal.tsx
  src/app/_components/sidebar/profileCard.tsx
  src/app/_components/sidebar/sideNews.tsx
  src/app/_components/sidebar/sidebarProfile.tsx
  src/assets/arrow-down.svg
  src/assets/arrow-up.svg
  src/assets/bookMark.svg
  src/assets/close.svg
  src/assets/edit.svg
  src/assets/favorite.svg
  src/assets/index.tsx
  src/assets/search.svg
  src/assets/setting.svg
  src/assets/shortcut.svg
  svgr.d.ts
Labels: 🐛 Fix

#30 [Feature/#25] 글자크기, 요약정도 컴포넌트 구현
  src/app/_components/font-size.tsx
  src/app/_components/option-selector.tsx
  src/app/_components/sidebar/index.tsx
  src/app/_components/sidebar/subscribe.tsx
  src/app/_components/summary.tsx
  src/assets/default.svg
  src/assets/detailed.svg
  src/assets/font-size.svg
  src/assets/index.tsx
  src/assets/simple.svg
Labels: 🌱 Add, ✨ Feat, 💄 Style

#35 [Feature/#32] 기사 상세 페이지 퍼블리싱
  public/images/image.png
  src/app/(route)/detail/[detail]/page.tsx
  src/app/(route)/detail/_components/.gitkeep
  src/app/(route)/detail/_components/action-bar.tsx
  src/app/(route)/detail/page.tsx
  src/app/_components/button.tsx
  src/app/_components/header.tsx
  src/app/_components/layout.tsx
  src/app/_components/sidebar/index.tsx
  src/app/_components/sidebar/trand-ranking.tsx
  src/app/_components/sidebar/tranding-news.tsx
  src/assets/bookmark.svg
  src/assets/heart.svg
  src/assets/index.tsx
  src/assets/like-filled.svg
  src/assets/like-outline.svg
  src/assets/logo-head.svg
  src/assets/share.svg
Labels: 🌱 Add, ✨ Feat, 💄 Style

#33 [Feature/#31] 마이페이지-북마크 (커스텀 부분)구현
  src/app/(route)/home/page.tsx
  src/app/(route)/my-page/_components/bookmark-folder-content.tsx
  src/app/(route)/my-page/_components/bookmark-folder-item.tsx
  src/app/(route)/my-page/_components/bookmark-folder-list.tsx
  src/app/(route)/my-page/_components/my-profile-card.tsx
  src/app/(route)/my-page/page.tsx
  src/app/(route)/search/page.tsx
  src/app/_constants/routes.ts
  src/app/_mocks/article-array.ts
  src/app/_mocks/book-mark-folders.ts
  src/app/_stores/use-bookmark-store.ts
Labels: 🌱 Add, ✨ Feat, ♻️ Refactor

#37 [Feature/#33] 설정 페이지 퍼블리싱
  components.json
  package.json
  pnpm-lock.yaml
  src/app/(route)/setting/page.tsx
  src/app/_components/button.tsx
  src/app/_components/font-size.tsx
  src/app/_components/input.tsx
  src/app/_components/sidebar/tranding-news.tsx
  src/app/_components/summary.tsx
  src/app/_constants/routes.ts
  src/app/_styles/components/ui/switch.tsx
  src/app/_styles/lib/utils.ts
  src/app/globals.css
  src/assets/favorite.svg
  src/assets/google.svg
  src/assets/index.tsx
  src/assets/kakao.svg
Labels: 🌱 Add, ✨ Feat, ♻️ Refactor

#38 [Feature/#34] 탈퇴페이지 퍼블리싱
  src/app/(route)/delete-account/page.tsx
  src/app/_constants/exit-reasons.ts
Labels: ✨ Feat

#43 [Feature/#42] API 제네릭 함수 설정
  package.json
  pnpm-lock.yaml
  src/app/(route)/home/_components/banner.tsx
  src/app/(route)/home/page.tsx
  src/app/(route)/snack-news/_components/index.tsx
  src/app/(route)/snack-news/page.tsx
  src/app/_apis/api.ts
  src/app/_apis/instance.ts
  src/app/_components/layout.tsx
  src/app/_constants/routes.ts
  src/assets/index.svg
  src/assets/index.tsx
  src/assets/left.svg
Labels: 🧹 Chore, ✨ Feat

#40 [Feature/#39] 북마크 모달창 구현
  src/app/(route)/detail/[detail]/page.tsx
  src/app/(route)/detail/_components/action-bar.tsx
  src/app/(route)/detail/_components/folder-modal.tsx
  src/app/(route)/my-page/_components/bookmark-folder-content.tsx
  src/app/(route)/my-page/_components/bookmark-folder-item.tsx
  src/app/(route)/my-page/_components/folder-upsert-modal.tsx
  src/app/(route)/my-page/page.tsx
  src/app/_components/input.tsx
  src/app/_constants/color.ts
  src/app/_stores/use-bookmark-store.ts
  src/assets/check.svg
  src/assets/co-auther.svg
  src/assets/folder-name.svg
  src/assets/index.tsx
  src/assets/info.svg
  src/assets/member-del.svg
  src/assets/tag.svg
  tsconfig.json
Labels: 🌱 Add, ✨ Feat, 💄 Style

#48 [Feature/#45] 시각화 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/app/(route)/detail/[detail]/page.tsx
  src/app/(route)/home/_components/banner.tsx
  src/app/(route)/home/_components/word-cloud-wrapper.tsx
  src/app/(route)/home/_components/word-cloud.tsx
  src/app/(route)/snack-news/_components/index.tsx
Labels: 🌱 Add, ✨ Feat
