Repository CURIO-DEV/CURIO-FE, pull requests merged in 2025-06, with the labels that each got.

#52 [Feature/#51] 실시간 트렌드 API 연결
  src/app/_apis/trends/trends-queries.ts
  src/app/_apis/trends/trends.ts
  src/app/_components/sidebar/trand-ranking.tsx
  src/app/_constants/api.ts
  src/app/_types/.gitkeep
  src/app/_types/trend.ts
  src/hooks/use-trends.ts
Labels: 🧹 Chore, ✨ Feat

#56 [Feature] 실시간 인기글 API 연결 및 디테일 페이지 id 수정
  src/app/(route)/detail/[id]/page.tsx
  src/app/_apis/article.ts
  src/app/_apis/trends/trends-queries.ts
  src/app/_apis/trends/trends.ts
  src/app/_components/sidebar/trand-ranking.tsx
  src/app/_components/sidebar/tranding-news.tsx
  src/app/_constants/api.ts
  src/app/_types/trend.ts
  src/hooks/use-article-headlines.ts
  src/hooks/use-article-summary.ts
  src/hooks/use-trends.ts
Labels: ✨ Feat

#60 [Feature/#59] 관심사 키워드 API 연결
  src/app/(route)/home/_components/word-cloud.tsx
  src/app/_apis/trends/trends-queries.ts
  src/app/_apis/trends/trends.ts
  src/app/_constants/api.ts
  src/app/_types/trend.ts
  src/hooks/use-trends.ts
Labels: ✨ Feat

#61 [Feature/#53] 카카오 및 구글 로그인 구현
  src/app/(route)/detail/[id]/page.tsx
  src/app/(route)/login/page.tsx
Labels: ✨ Feat

#57 [Feature/#55] 검색페이지 api연결
  src/app/(route)/detail/[id]/page.tsx
  src/app/(route)/search/page.tsx
  src/app/_apis/article.ts
  src/app/_apis/search.ts
  src/app/_components/article.tsx
  src/app/_components/header.tsx
  src/app/_components/sidebar/trand-ranking.tsx
  src/hooks/use-search-articles.ts
Labels: ✨ Feat, ♻️ Refactor

#80 [Feature/#78] 탈퇴페이지 api연결 및 공유버튼 기능 구현
  next.config.ts
  src/app/(route)/delete-account/page.tsx
  src/app/(route)/detail/_components/action-bar.tsx
  src/app/_apis/delete-account.ts
  src/hooks/use-delete-accout.ts
Labels: ✨ Feat

#83 [Refactor/#82] 스타일 수정 관련 리팩토링
  src/app/(route)/home/page.tsx
  src/app/(route)/my-page/_components/my-profile-card.tsx
  src/app/_components/header.tsx
  src/app/_components/sidebar/subscribe.tsx
  src/hooks/use-user.ts
Labels: ♻️ Refactor, 💄 Style
